---
  language: node_js

  node_js:
    - stable

  script: make lint test

  addons:
    code_climate:
      repo_token: 4b5aa044f2b0c920f8e13548a0ebb90ecc1210f246443542941a843385bb28d0

  after_success:
    - npm install -g Istanbul cover
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < lcov.info
